#!/bin/bash

echo "[post-commit hook] Commit done!"

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

# Ask if the user wants to reload their dotfiles
printf  "\033[1mDo you want to reload your dotfiles? (y/N)\033[0m [Y/n] "
read -r response

if [[ "$response" =~ ^([nN][oO]|[nN])$ ]]; then
    echo
    echo "Reloading dotfiles..."
    dfr
fi
