#!/bin/bash

# Ask if the user wants to reload their dotfiles
read -p "Do you want to reload your dotfiles? (y/n) " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo "Reloading dotfiles..."
    dfr
fi
