function fish_greeting
    printf '\e[36m'
    printf '\e[38;5;196m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n'
    printf '\e[38;5;196m┃                                                                              ┃\n'
    printf '\e[38;5;196m┃                             .mmMMMMMMMMMMMMMmm.                              ┃\n'
    printf '\e[38;5;196m┃                         .mMMMMMMMMMMMMMMMMMMMMMMMm.                          ┃\n'
    printf '\e[38;5;196m┃                      .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.                       ┃\n'
    printf '\e[38;5;196m┃                    .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                     ┃\n'
    printf '\e[38;5;202m┃                  .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                   ┃\n'
    printf '\e[38;5;202m┃                 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                  ┃\n'
    printf '\e[38;5;202m┃                MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                 ┃\n'
    printf '\e[38;5;202m┃               MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                ┃\n'
    printf '\e[38;5;208m┃              .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.               ┃\n'
    printf '\e[38;5;208m┃              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM               ┃\n'
    printf '\e[38;5;208m┃              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM               ┃\n'
    printf '\e[38;5;208m┃              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM               ┃\n'
    printf '\e[38;5;214m┃              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM               ┃\n'
    printf '\e[38;5;214m┃              `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`               ┃\n'
    printf '\e[38;5;214m┃               MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                ┃\n'
    printf '\e[38;5;214m┃                MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                 ┃\n'
    printf '\e[38;5;220m┃                 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                  ┃\n'
    printf '\e[38;5;220m┃                  `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`                   ┃\n'
    printf '\e[38;5;220m┃                    `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`                     ┃\n'
    printf '\e[38;5;220m┃                      `"MMMMMMMMMMMMMMMMMMMMMMMMMMMMM"`                       ┃\n'
    printf '\e[38;5;226m┃                         `"MMMMMMMMMMMMMMMMMMMMMMM"`                          ┃\n'
    printf '\e[38;5;226m┃                             `""MMMMMMMMMMMMM""`                              ┃\n'
    printf '\e[38;5;226m┃                                                                              ┃\n'
    printf '\e[38;5;226m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n'
    printf '\e[0m'
end
