#!/usr/bin/env bash

if [ -z "$*" ]
  then
    echo "Error: missing query for ChatGPT."
    exit 1
fi

if [[ -z "${OPENAI_API_KEY}" ]]; then
  echo "Error: OPENAI_API_KEY environment variable is not set."
  exit 1
fi

# Use a heredoc to support a multiline query to the API
query=$(cat <<EOF
$*
EOF
)
query=$(echo "$query" | tr '\n' ' ')

response=$(curl -sS https://api.openai.com/v1/chat/completions \
        -H "Authorization: Bearer $OPENAI_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": "'"$query"'"}]
      }')

printf "$(echo $response | jq -r '.choices[0].message.content')\n"

