#!/usr/bin/env bash

if [[ " $* " != *" --install-packages "* ]]; then
    echo "⚠️ SKIPPING PACKAGE INSTALLS"
    echo "To install packages, run this script with the '--install-packages' option."
    cd $HOME/github.com/$GITHUB_HANDLE/dotfiles && gdn && $HOME/github.com/$GITHUB_HANDLE/dotfiles/install.sh --skip-packages $*
else
    cd $HOME/github.com/$GITHUB_HANDLE/dotfiles && gdn && $HOME/github.com/$GITHUB_HANDLE/dotfiles/install.sh $*
fi
