#!/usr/bin/env bash

initial="$@"
branch=$(git branch --all | sed "s/*//" | sed "s/remotes\/origin\///" | fzf --query "$initial" | tr -d '[:space:]')
if [ -n "$branch" ]; then
	git checkout "$branch"
fi
