#!/usr/bin/env bash
##################################################################
# Exits with 0 if given directory is both a git repo and has file
# changes not staged for commit.
# Exits with 1 otherwise.
##################################################################
git_is_repo || exit 1
git diff-files --quiet --exit-code || exit 0
exit 1
