#!/usr/bin/env bash
 if $(git_is_repo); then
    name1="$(command git symbolic-ref --short HEAD 2> /dev/null)"
    if [ -n "$name1" ]; then
        echo "$name1"
    else
        echo "$(command git show-ref --head -s --abbrev | head -n1 2> /dev/null)"
    fi
fi
