#!/usr/bin/env bash

set -e

COMMIT_MESSAGE="${*:-"update"}"

git commit --message "$COMMIT_MESSAGE"

printf  "\033[1mDo you want to push the changes?\033[0m [Y/n] "

read -r response

if [[ "$response" =~ ^([nN][oO]|[nN])$ ]]; then
  echo "Changes were not pushed."
fi

echo "Pushing changes..."
gup
