#!/bin/bash
set -e

# Check if PR is passing CI
if ! gh pr checks $(git_branch_name); then
  echo "CI checks failed. Aborting merge."
  exit 1
fi

PR_TITLE=$(gh pr view $(git_branch_name) --json title --jq .title)

# Merge the PR
gh pr merge --squash $(git_branch_name) --subject "$PR_TITLE"

# Check out latest main branch
git checkout main
git pull
