#!/usr/bin/env bash

set -e
set -o pipefail

# exit if docker command not installed
if ! command -v docker > /dev/null; then
	echo "This command requires docker to be installed"
	exit 1
fi

if [ -z "$1" ]; then
    printf "No input move file was supplied\n\n"
    echo "Usage: mov2gif <path-to-mov-file>"
    exit 1
fi

cp "$1" $HOME/images/image.mov

docker run \
    --platform linux/amd64 \
    --rm -it -v $HOME/images:/images \
    --entrypoint='' \
    jrottenberg/ffmpeg /images/gifenc.sh /images/image.mov /images/image.gif

DEST_FILE="$HOME/downloads/"$(basename -s '.mov' $1)".gif"

cp $HOME/images/image.gif "$DEST_FILE"

echo "🎉 Done! View your gif at '$DEST_FILE'"
