#!/usr/bin/env bash

SHORTCUT_NAME=$1
shift

/bin/cat << EOF > $PERSONAL_SCRIPTS_DIR/$SHORTCUT_NAME
#!/usr/bin/env bash
# Generated with shortcut command:
#
#   shortcut $SHORTCUT_NAME '\$*'

$* \$*
EOF

chmod +x $PERSONAL_SCRIPTS_DIR/$SHORTCUT_NAME
