name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:

env:
  IMAGE_NAME: dotfiles
  DOCKERFILE_PATH: ./Dockerfile
  DOCKER_BUILD_ARGS: ""

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }},latest
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
